[package]
name = "WasmtimeTest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "12.0.1"
scripting_runtime = {version = "0.1.0", path = "../scripting_runtime" }
