[package]
name = "brane_engine_api"
version = "0.1.0"
edition = "2021"
authors = ["WireWhiz"]
description = "API for Brane Engine scripting"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brane_engine_api_macros = { version = "0.1.0", path = "macros" }
memoffset = "0.9"

