[workspace]
members = [
    "testScripts1",
    "testScripts2"
]


[workspace.dependencies]
brane_engine_api = { version = "0.1.0", path = "../scripting_runtime/api" }
proc-macro2 = "1.0.66"
syn = "2.0.28"