[package]
name = "TestWasmScripts"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wasm_crate"
path = "testScript.rs"
crate-type=["cdylib"]

[dependencies]
brane_engine = { version = "0.1.0", path = "../BraneEngineAPI" }
wasm-bindgen = "0.2.87"

[build-dependencies]
proc-macro2 = "1.0.66"
syn = "2.0.28"