[package]
name = "testScript1"
version = "0.1.0"
edition = "2021"

[lib]
name = "wasm_crate1"
path = "testScript1.rs"
crate-type=["cdylib"]

[dependencies]
brane_engine_api.workspace = true

[build-dependencies]
proc-macro2.workspace = true
syn.workspace = true

